### PR TITLE
Filter Images by Minimum Rating

### PR DESCRIPTION
**Pull request by KANDUKURIsaikrishna**

### CODE REVIEW

**Comment by KANDUKURIsaikrishna** [comment]
Hey i have tried to resolve the conflict can please help me.

**Comment by KANDUKURIsaikrishna** [comment]
I got it i have resolved issues

**Comment by iamDyeus** [comment]
Hey @KANDUKURIsaikrishna, great work! A pull request (#17) was merged, which implemented logging in `image_manager.py` and caused merge conflicts with your PR. Please resolve these conflicts and then ping me. 😄

**Comment by KANDUKURIsaikrishna** [comment]
Hey @iamDyeus I have resolved the conflict. Please have a look at it

**Comment by iamDyeus** [comment]
Looks great to me!

**Pull request merged**
