### PR TITLE
Update test_main.py

### PR DESCRIPTION
**Pull request by RishiAnand108**
Updated Documentation (README.md)
# Project Name

## Running Tests

To run the tests, use the following command:

```bash
python -m unittest discover tests

2)Test Coverage
bash
coverage run -m unittest discover tests
coverage report -m


3)Contributing
Please ensure any new code is covered by tests. Follow the naming conventions for test files (test_<name>.py) and add tests for any new functionalities or changes in the codebase.


By following these steps, we ensure that our test suite is well-organized, up-to-date, and provides sufficient coverage for core functionalities, smoothly integrating with the CI pipeline. If you have any further adjustments or additional requirements, feel free to let me know!

### CODE REVIEW

**Comment by RishiAnand108** [comment]
sir accept and merge ot under hacktober fest

**Comment by iamDyeus** [comment]
There's a similar PR (#20) open related to testing. Please review your changes against that PR and ping me once you've made any substantial improvements. Currently, I don’t see much progress here.

**Comment by RishiAnand108** [comment]
i am not avialable

**Comment by RishiAnand108** [comment]
sir but these is not merged under the pr of hacktober fest

**Comment by RishiAnand108** [comment]
in hacktober it is not shown

**Comment by iamDyeus** [comment]
> sir but these is not merged under the pr of hacktober fest

I haven’t merged this pull request yet, as it may cause conflicts with PR #20. It might be best to rethink the implementation and make substantial improvements. I’ll go ahead and close this PR for now. Once PR #20 is merged, please create a new PR with your changes.

**Pull request closed without merging**
